# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Set up Anaconda
          command: |
            wget -q http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh;
            chmod +x ~/miniconda.sh;
            ~/miniconda.sh -b -p ~/miniconda;
            echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;

      - run:
          name: Create environment and contrive to always use it
          command: |
            conda update --yes --quiet conda;
            export CONDA_EXE=/home/circleci/miniconda/bin/conda
            make create_environment
            conda init bash
            sed -ne '/>>> conda initialize/,/<<< conda initialize/p' ~/.bashrc >> $BASH_ENV
            echo "conda activate easydata-tutorial" >> $BASH_ENV;

      - run:
          name: Create test report directory
          command: |
            mkdir test-reports

      # Cache dependencies
      - save_cache:
          key: pip-cache
          paths:
            - ~/.cache/pip

      - restore_cache:
          keys:
            - pip-cache

      - run:
          name: Run tests
          command: |
            make test CI_RUNNING=yes

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
